### ISSUE TITLE
Client configuration does not use COMPUTERNAME at all

### ISSUE THREAD

**Issue by bkraul** [hejare/urbackup-client#2]
I used to install the urbackup client on the actual host, but I am trying to do it through a container now. I am putting the client on the same compose stack as the server, using the proper mounts, and a network between the two.

The server is seeing the clients, and the backups works. Everything works, really, except the fact that every time the stack is destroyed and recreated, the client uses a new, random-generated name, therefore, I end up with endless backups of the same thing:

![image](https://user-images.githubusercontent.com/14616851/69633449-d90bac80-1015-11ea-8ddf-d59417d444f4.png)
![image](https://user-images.githubusercontent.com/14616851/69633804-867ec000-1016-11ea-8bcb-e597201acf04.png)

Here is my docker-compose:
```yml
version: '2.4'
services:
  urbackup:
    image: uroni/urbackup-server
    restart: always
    ports:
      - '55415:55415'
      - '35623:35623/udp'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/docker-persist/urbackup/database:/var/urbackup
      - ~/backup:/backups
    environment:
      - VIRTUAL_HOST=urbackup.mydomain.com
      - VIRTUAL_PORT=55414
      - HTTPS_METHOD=noredirect
    networks:
      - reverse-proxy
      - default
  urbackup-client:
    image: hejare/urbackup-client
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/dev-disk-by-label-NAS:/backup/nas:ro
    environment:
      - COMPUTERNAME=nas
    networks:
      - default

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
```
As you can see, there is no need to declare the ports for the client, because it is in the same default network as the client.

It would be great if it could actually use the same name/identifier, even after recreate.
